### PR TITLE
Parse empty files

### LINKED ISSUE #149: Parse empty files

### PR DESCRIPTION
**Pull request by jannis-baum**
Close #149

### CODE REVIEW

**Comment by jannis-baum** [comment]
One caveat here is of course that you have to save the file before you can open Vivify, on a new buffer that is not saved yet this won't work because Vivify is organized in parallel to the file system

**Comment by tuurep** [comment]
Yes, exactly what I was after! Thanks!

Also tested with an extensionless file, and opens this:

image

Whereas before it would have asked me if I want to save file, because of this firefox setting I think:

image

And showing the empty text file is much better in my opinion

**Review by tuurep — APPROVED** [review]

**Comment by jannis-baum** [comment]
Nice! Happy this was so easy for once hahahaha

> Whereas before it would have asked me if I want to save file, because of this firefox setting I think:

Yeah files with `shouldRender(...) == false` will be sent as data which is necessary e.g. to render local images in Markdown files. And browsers will do the download when they get data.

**Comment by Tweekism** [comment]
On Windows, this will be `application/x-empty`

Mental note for me for later...

**Comment by tuurep** [comment]
Btw this doesn't behave so well when you delete all contents in a file while previewing,

* rather than empty buffer, shows last non-empty contents
* if you save it as empty and re-view, still shows the last non-empty contents

But I'm not sure how much is related to:

> Vivify is organized in parallel to the file system

Is it changing the `file` -type on the fly, if you know what I mean?

**Comment by jannis-baum** [comment]
@tuurep Ah okay, this is probably because the empty string resolves to "false" so it doesn't update it and then it still has the live content saved when you reopen it. I'll fix that later :)

**Comment by tuurep** [comment]
Nice, sounds like an easy problem :smile:

**Pull request merged**
