### PR TITLE
Add new issues to project board

### LINKED ISSUE #124: Add new issues to project board

### PR DESCRIPTION
**Pull request by jannis-baum**
Close #124

### CODE REVIEW

**Comment by jannis-baum** [comment]
Hey @tuurep @Tweekism!

I invited you to the new (non-public) Vivify project board. It has all issues from this and the Vim plugin repo and should make it easier to maintain an overview of what's going on. The idea there is that we grab unassigned issues we want to work on and drag them into our sections of the table in the order we want to do them in :) This way we can more easily see what the others' next plans are.

**Comment by Tweekism** [comment]
Is that this projects tab at the top? There is no projects in there yet for me. Or is it only new issues added from now on?

image

**Comment by jannis-baum** [comment]
> Is that this projects tab at the top? There is no projects in there yet for me. Or is it only new issues added from now on?

Ah yes, I hadn't linked it. Now it should be there :)

**Comment by tuurep** [comment]
Cool, I took a look and seems straight forward

**Comment by tuurep** [comment]
I'm going to sort my rows in the order of priority/what I'm actually gonna do first

**Comment by jannis-baum** [comment]
> I'm going to sort my rows in the order of priority/what I'm actually gonna do first

Yes, perfect, that's the idea! :) Thanks!

**Pull request merged**
