### PR TITLE
Task-list checkbox alignment

### LINKED ISSUE #131: Task list alignment issue
From https://github.com/jannis-baum/Vivify/pull/70#issuecomment-2226902971

> Btw quite disturbing:
>
> image
>
> How the checkbox isn't aligned to the text. I might look into that next 😄

### PR DESCRIPTION
**Pull request by tuurep**
Close #131 

Ready for review @jannis-baum 

Test doc:

```md
## Simple

- [ ] foo
- [x] bar
- [ ] baz

## Complicated

* foo
- [ ] foo
    - bar
        - [x] baz
    - [ ] bar
        * baz
        1. baz
            - [x] qux
            * qux
        2. baz
- [x] foo

```

image

### CODE REVIEW

**Comment by tuurep** [comment]
Solution in #102 icon alignment can't be used here

This has been quite a rabbit hole, the way GitHub does this is (essentially):

```css
#checkbox {
  display: inline-block;
  vertical-align: middle;
  margin: 0 .2em .25em -1.4em;
}
```

So the `vertical-align: middle` doesn't look quite right until adding some `margin-bottom`

But I quite liked how you'd managed to align the text within different types of list bullet types with the `transform: translateX(1.44rem)`

And setting the GitHub margins by copying them exactly throws that off plus adds quite a bit of extra vertical spacing to the whole "complicated" list.

So I reused the GH idea, but tried to only achieve the vertical alignment of the icon without changing other proportions.

But note: the right margin `-1.125rem` is not exact, looks quite perfect in the screenshot but depends on:
* font (probably)
* zoom level
* browser-specifics: Vivaldi uses a different checkbox icon and has a tiny difference

But in all above cases the difference is quite tiny and I felt like it's overall a definite improvement, so here's my proposed change.

**Review by jannis-baum — APPROVED** [review]
This looks great, definitely a big improvement! Not sure if I understood everything you explained. I tried zooming around and that didn't break anything and on Safari it looks perfect as well. Not sure about the font but it would probably have to be very exotic to break it, and if it does then that person can also fix the alignment in their custom CSS ^^ 

Feel free to merge this!😊

**Comment by tuurep** [comment]
Heh, definitely too much detail for such a tiny change

I was a bit worried about the magic-number quality of the two margins but that's great to know that they look just right on your setup as well

Alright, merging. Thanks!

**Comment by Tweekism** [comment]
Alignment looks good here too! I liked your simple and complicated layout check, you should consider adding that to the rendering tests :)

Sorry I've been away so long, I had a funeral to attend, then kid events and then my Wife tasked me with setting up Immich as a Google Photos replacement (Google has started to make her pay for storage). That last project is ongoing, but I didn't know where, or if, I should post that randomly is some thread somewhere.

Maybe we need a general / off-topic chat or a discord or something :)

**Comment by tuurep** [comment]
Thanks good to know!

Yeah, maybe could be useful in the test doc, however since the example I made is far from a practical scenario I didn't add it here :D But yeah I could add a little "mixed types of lists" test there.

Yeah no worries, prioritizing other stuff over open source from time to time is such a natural thing.

> That last project is ongoing, but I didn't know where, or if, I should post that randomly is some thread somewhere.

Sorry I don't know what you mean, which project :smile: the Immich transfer?

But yes I don't mind sharing my discord for example. Same handle @tuurep feel free to add

**Comment by Tweekism** [comment]
> Sorry I don't know what you mean, which project 😄 the Immich transfer?

Ha, na I just meant like, I wanted to say "Hey guys, gunna be gone for a while, not sure when I'll be back on but will keep you posted" but I didn't know where best to say it :P

**Comment by tuurep** [comment]
Oh I see what you mean

Yep, a chat would be useful

**Comment by jannis-baum** [comment]
Yes, totally normal and fine to have other stuff going on! I've also been less active because I'm about to go to Colombia for six months so lots of stuff to organize

Good idea about a chat. Do you guys use Telegram? I also have Discord but I find it hard to keep up with

**Comment by tuurep** [comment]
Yes that's also fine

**Comment by jannis-baum** [comment]
> Yes that's also fine

Nice! My Telegram is `jannisbaum`. If Telegram also works for @Tweekism let's set up a group there!

**Comment by Tweekism** [comment]
Hmm never use Telegram will have to have a look.

Do use signal, discord and messenger for family chats.

**Comment by jannis-baum** [comment]
Signal would also work for me

**Comment by tuurep** [comment]
I can be flexible (never tried Signal but would be interested to try)

**Comment by jannis-baum** [comment]
@Tweekism we made a group, could you share your Signal username here? Or, if you want to keep it private let me know, then I can tell you my Signal username here and you text me :)

**Comment by Tweekism** [comment]
I am tweekism.42

**Pull request merged**
