### PR TITLE
Fix config.json issues

### LINKED ISSUE #33: Various config.json issues
### Unlisted dependency on `jq`

Hi, the primary reason I filed this under "bug" is that I noticed to use the `config.json` file in the first place requires package `jq` to be installed on the user's system but this is not listed as a dependency for the project anywhere. I didn't have this installed and that was hard to pinpoint :smile: 

So for example, this package is a Vivify dependency for me: https://archlinux.org/packages/extra/x86_64/jq/

Maybe the readme should have a Dependencies -section, and do you know if there could be more?

### `"pageTitle"` doesn't seem to work with `basename` or `join`

If my goal is to set the pagetitle as `basename(path)`, what should I set on the key? I figured it should be this:

```
{
    "pageTitle": "basename(path)"
}
```

However each time I try this, using `viv` gives an "Unable to connect" firefox page.

What has worked as a `"pageTitle"` key:

* `"'foo'"` will show <title> as `foo`
* `"console.log('foo')"` will show <title> as `undefined` (correct, I think :smile: )
* `"path"` will show the full path, which is a good sign
  * Also: `"console.log(path)"` correctly shows `undefined`

Same issue (Unable to connect) applies for trying to use the `join` func, as an example:

* `"join('foo', path)"`

This is what the Firefox page looks like:

image

### PR DESCRIPTION
**Pull request by jannis-baum**
Close #33

### CODE REVIEW

**Comment by tuurep** [comment]
Great, thank you! It's a fix, got my preferred title with either:

* "\`${basename}\`"
* "basename"

Tried something like:

* "\`${basename} in ${dirbasename}\`"

and works as expected. JSON's mandatory doublequotes can be a bit awkward but that's just JSON.

I couldn't however find where the logging is output on a title error, nothing in either firefox dev console or terminal. But it's a big improvement, still rendering the page and knowing there was a title error.

**Review by tuurep — APPROVED** [review]
I think this is fine, but if you're concerned about me not finding the logs, let me know.

**Comment by jannis-baum** [comment]
> I think this is fine, but if you're concerned about me not finding the logs, let me know.

Okay, just confirmed the problem. The way I'm doing it now works with Safari but not Firefox. Will adjust later & then let you know :)

**Comment by jannis-baum** [comment]
@tuurep I switched to writing the error message straight onto the page, what do you think?

**Comment by tuurep** [comment]
Yes, this works great. Thanks & ready to merge

image

^ sorry I don't know what this means, I figured it's probably nothing but if it requires something from me let me know :smile:

**Pull request merged**
